function [ ROI_boundary_points ] = ROI_points_dilb( facial_landmarks )
%select 8 facial landmarks to define ROI, the landmark numbers are
%2,4,6,9,12,14,16,29
width1=(facial_landmarks(16,1)-facial_landmarks(2,1))*0.05;
width2=(facial_landmarks(14,1)-facial_landmarks(4,1))*0.05;
width3=(facial_landmarks(12,1)-facial_landmarks(6,1))*0.05;
height=(facial_landmarks(9,2)-facial_landmarks(29,2))*0.1;
nose_shift=(facial_landmarks(29,1)-facial_landmarks(2,1))*0.2;
height2=(facial_landmarks(6,2)-facial_landmarks(4,2))*0.4;


ROI_boundary_points=[facial_landmarks(2,1)+width1,facial_landmarks(2,2);...
                     facial_landmarks(4,1)+width2,facial_landmarks(4,2);...
                     facial_landmarks(6,1)+width3,facial_landmarks(6,2)-height2;...
                     facial_landmarks(34,1),facial_landmarks(34,2);...
                     facial_landmarks(12,1)-width1,facial_landmarks(12,2)-height2;...
                     facial_landmarks(14,1)-width2,facial_landmarks(14,2);...
                     facial_landmarks(16,1)-width3,facial_landmarks(16,2);...
                     facial_landmarks(29,1)+nose_shift,facial_landmarks(29,2)+height;...
                     facial_landmarks(29,1)-nose_shift,facial_landmarks(29,2)+height];
end

